apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespaces-pss-privileged.yaml

patches:
- path: configmap-patch.yaml
- target:
    kind: Namespace
    name: kubeflow
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kubeflow
      labels:
        pod-security.kubernetes.io/enforce: privileged
- target:
    kind: Namespace
    name: kubeflow-system
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kubeflow-system
      labels:
        pod-security.kubernetes.io/enforce: privileged
- target:
    kind: Namespace
    name: oauth2-proxy
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: oauth2-proxy
      labels:
        pod-security.kubernetes.io/enforce: privileged
- target:
    kind: Namespace
    name: auth
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: auth
      labels:
        istio-injection: enabled
        pod-security.kubernetes.io/enforce: privileged
- target:
    kind: Namespace
    name: knative-serving
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: knative-serving
      labels:
        istio-injection: enabled
        pod-security.kubernetes.io/enforce: privileged
- target:
    kind: Namespace
    name: istio-system
  patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: istio-system
      labels:
        pod-security.kubernetes.io/enforce: privileged
- target:
    kind: Deployment
    name: istiod
    namespace: istio-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ISTIO_CNI_ENABLED
        value: "false"
- target:
    kind: DaemonSet
    name: istio-cni-node
    namespace: kube-system
  patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: istio-cni-node
      namespace: kube-system
    $patch: delete
