apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cap-admin
  labels:
    app.kubernetes.io/name: cap-admin
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: istio
rules:
# Core networking permissions
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]

# Network policy management
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# CNI and networking configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# Events for logging and debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# Istio-specific permissions
- apiGroups: ["security.istio.io"]
  resources: ["peerauthentications", "requestauthentications"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["networking.istio.io"]
  resources: ["destinationrules", "envoyfilters", "gateways", "serviceentries", "virtualservices", "workloadentries", "workloadgroups"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Pod mutation permissions for sidecar injection
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "update", "patch"]