apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- configmap.yaml
- daemonset.yaml

commonLabels:
  app.kubernetes.io/name: cap-admin
  app.kubernetes.io/component: networking
  app.kubernetes.io/part-of: istio