apiVersion: v1
kind: ServiceAccount
metadata:
  name: cap-admin
  namespace: istio-system
  labels:
    app.kubernetes.io/name: cap-admin
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: istio