apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespaces-pss-privileged.yaml

components:
- ../../../../oauth2-proxy/components/istio-external-auth-patches

patches:
- target:
    kind: Deployment
    name: istiod
    namespace: istio-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ISTIO_CNI_ENABLED
        value: "false"
- target:
    kind: DaemonSet
    name: istio-cni-node
    namespace: kube-system
  patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: istio-cni-node
      namespace: kube-system
    $patch: delete